### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by TheEvilSkeleton** [Yochyo/Yummybooru#1]
Any plan on submitting this wonderful app in F-Droid?

**Comment by Yochyo** [comment]
No reason not to. I will check it out.

**Comment by Yochyo** [comment]
Adding the app to an app store is a great idea. I never heard of f-droid before and will check it out. It seems like submitting an app is a long process though.
I also thought about trying to get it on the play store again.

**Comment by TheEvilSkeleton** [comment]
Yeah, unfortunately it takes a while because F-Droid is really restrictive; not only your app must be FOSS, it is also required to not have proprietary code as well. And they build all the apps from source.

In the meantime, you can create your own F-Droid repository: https://f-droid.org/en/repomaker/. I could submit an MR in an F-Droid client like Aurora Droid to include the repo.

**Comment by Yochyo** [comment]
Hey, sorry for the late answer. It seems like I'm not getting any notifications from issues.

I will not release the app on F-Droid for the following reasons.

1) F-droid does not allow apps using google services, including Crashlytics which I am heavily dependant 
2) I will try to release it on the play store again. I released it on the play store previously but it got banned 2 times. The first time because I took a bad screenshot that included nudity. The second time because of my app description (Probably because I linked danbooru/konachan/yande.re directly)
3) F-droid seems to be aimed at a small target group (people without play store), it's just not worth the extra effort.

**Comment by Yochyo** [comment]
If anyone wants to, he can fork this project and add it to F-droid himself. You'd have to remove Crashlytics and the auto-updater.
Also, you'd probably want to merge Yummybooru, BooruApi, EventCollection, Downloader and EventManager_Kotlin into one repository. Those are all local dependencies I'm using for the app.

In general, anyone is free to use this code for non-commercial uses as long as he links this repository.

**Comment by TheEvilSkeleton** [comment]
That's understandable. Also thank you.
